### ISSUE TITLE
Failing to install on TS-431P

### ISSUE THREAD

**Issue by chrisbrownie** [ivokub/tailscale-qpkg#1]
G'day Ivo! 

Firstly, thanks for building this, it is exactly what I'm after...except I'm having some trouble. I built the package on wsl2/ubuntu with docker. Seems to work, as it spits out the files I'd expect:

```
-rwxrwxrwx 1 chris chris 12095490 Aug 13 20:20 Tailscale_1.0.3_arm_64.qpkg
-rwxrwxrwx 1 chris chris       71 Aug 13 20:20 Tailscale_1.0.3_arm_64.qpkg.md5
-rwxrwxrwx 1 chris chris 12557960 Aug 13 20:20 Tailscale_1.0.3_x86.qpkg
-rwxrwxrwx 1 chris chris       68 Aug 13 20:20 Tailscale_1.0.3_x86.qpkg.md5
-rwxrwxrwx 1 chris chris 13085648 Aug 13 20:20 Tailscale_1.0.3_x86_64.qpkg
-rwxrwxrwx 1 chris chris       71 Aug 13 20:20 Tailscale_1.0.3_x86_64.qpkg.md5
```

The challenge I'm having is that when I try to install it on my TS-431P (arm64, x86, or x64 package), I get the following error:

```
[App Center] Failed to install Tailscale1.0.3. The installation package is incompatible. Use the compatible package.
```

Looking at the Makefile, I suspect I should be seeing an `arm32` package which is what I'm guessing my NAS wants, given the below. 

```
# uname -a
Linux qnap 4.2.8 #2 SMP Wed Jul 29 05:53:49 CST 2020 armv7l unknown
```

Do I need to do something different to build this?

Cheers,
Chris

**Comment by chrisbrownie** [comment]
Okay, progress! I had to build the `arm-x41` qpkg. Will submit a PR 👍

**Comment by ivokub** [comment]
Hi Chris,

Thanks for testing it out and submitting a pull request! Greatly appreciate your contribution!

Best,
Ivo
