### ISSUE TITLE
Downloading problem

### ISSUE THREAD

**Issue by estimadarocha** [ivokub/tailscale-qpkg#11]
when i go to actions and try to download last build it gives me a 404, is this normal?

**Comment by ivokub** [comment]
No, it shouldn't give 404.

Latest build is at https://github.com/ivokub/tailscale-qpkg/actions/runs/524341216 and the created packages at https://github.com/ivokub/tailscale-qpkg/suites/1934182341/artifacts/38170404.

However, it seems that the access is only allowed for logged-in users. Were you logged in to Github when trying to access the built packages?

**Comment by estimadarocha** [comment]
yes it was because of not being logged!

thanks

small apart: i can ssh qnap can access webinterface but can't reach shares with tailscale ip, am i missing something?

**Comment by ivokub** [comment]
Is the share available directly (i.e. from a local network)? If so, then it could be a firewall or service binding issue. I would recommend checking that firewall does not prevent connections from other subnets (if enabled, then add a rule for enabling connections from 100.64.0.0/10). Check also that Service binding is disabled or configured properly (Control panel>Network and file services>network access>enable service binding).

**Comment by estimadarocha** [comment]
![image](https://user-images.githubusercontent.com/17991728/107042001-1ee70780-67b9-11eb-8230-a9bc7d1981a1.png)
as you can see the option is not enabled and when it's not enable it means services are binded to all interfaces. right?
