### ISSUE TITLE
Can't install Tailscale: "Invalid file format. Please contact the package developer."

### ISSUE THREAD

**Issue by MoSattler** [ivokub/tailscale-qpkg#117]
I am trying to install Tailscale on my QNAP.

DSM: DSM 7.2-64570 Update 3
Model: DS920+
CPU: INTEL Celeron J4125

I got to Package Manager > Manual Install and select `Tailscale_1.48.1-1_x86_64.qpkg`. 

This always fails with this message
> Invalid file format. Please contact the package developer.

After that, I tried every single package offered [here](https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.48.2), but the error remains.

**Comment by DentonGentry** [comment]
A DS920+ running DSM 7.2 is a Synology device, not QNAP. The Synology packages are available from https://pkgs.tailscale.com/stable/#spks or from the Synology Package Center.
