### ISSUE TITLE
Update to 1.4.4?

### ISSUE THREAD

**Issue by bradfitz** [ivokub/tailscale-qpkg#12]
Hi, I work at @tailscale. Thanks for packaging this!

Do you need any help updating this packaging to Tailscale 1.4.4? It seems stuck at 0.97?

**Comment by ivokub** [comment]
Hi @bradfitz, thanks for the great tool!

The packaging scripts work well for every version of Tailscale. If you want to build the package for the latest Tailscale version, then set the `TSTAG` environment variable during the build to the corresponding Tailscale tag, i.e. `TSTAG=v1.4.4 make out/pkg`. The build script then checks out the source code of the Tailscale client at the specified version and uses that to create the package. If no TSTAG environment variable is set, then the hardcoded default v0.9.7 is used.

I haven't figured out a nice way for the packaging script to follow the current version of Tailscale. Updating this repository to change the hardcoded variable with every Tailscale version seems excessive and I do not want to perform network operations in Makefile. 

However, for Github Actions, the latest tag is fetched automatically from Tailscale repository (see https://github.com/ivokub/tailscale-qpkg/blob/5c3447354f746ec00865374111c715033ca9bf98/.github/workflows/build.yml#L18). The Action runs weekly and lets you download the latest version at https://github.com/ivokub/tailscale-qpkg/actions.

If you have any ideas how this repository could follow the latest Tailscale version, then I would gladly implement it.

**Comment by coccyx** [comment]
This issue was helpful. I spent a few minutes trying to figure out where `upload-artifact` put things. Thanks!

**Comment by ivokub** [comment]
I added a new workflow which creates new release on a tag. The built packages for v1.4.4 is now available from https://github.com/ivokub/tailscale-qpkg/releases/tag/v1.4.4.
