### ISSUE TITLE
Unable to start service when built.

### ISSUE THREAD

**Issue by RamboRogers** [ivokub/tailscale-qpkg#17]
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscale -socket /var/run/tailscale/tailscaled.sock up
Failed to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] #

**Comment by ivokub** [comment]
There seems to be an additional `/` in the beginning of the socket path. Could you try:
```
./tailscale -socket var/run/tailscale/tailscaled.sock up
```

(The reason for having the unix socket in the package directory is that the rest of the file system is overwritten during firmware update and we do not get persistence)
