### ISSUE TITLE
Correctly expose version info

### ISSUE THREAD

**Issue by guidoiaquinti** [ivokub/tailscale-qpkg#18]
👋 First of all: nice work! I was able to install `tailscale` on my QNAP in ~10 min thanks to this repo.

An issue that I found is that the current [`build.sh`](https://github.com/ivokub/tailscale-qpkg/blob/master/build/build.sh) doesn't expose the canonical version number in the binary as it should. We can probably use https://github.com/tailscale/tailscale/blob/main/build_dist.sh#L3-L10 to make it happening.

**Comment by ivokub** [comment]
Sounds reasonable. I also think the currently displayed version number is confusing.
