### ISSUE TITLE
Verify QVPN dependency requirement

### ISSUE THREAD

**Issue by ivokub** [ivokub/tailscale-qpkg#22]
I recall that tun module was not available without installing QVPN package. However, https://github.com/tailscale/tailscale/issues/1346 suggests otherwise.

**Comment by GoetzGoerisch** [comment]
@ivokub I can confirm that building and installing a pkg without:
https://github.com/ivokub/tailscale-qpkg/blob/d34ed19496f6aab2dd50b48427b51c53b32a9e7a/build/build-qpkg.sh#L29
works fine on QTS 5.0.0.1853 on x86_64.
