### ISSUE TITLE
Can use my qnap as exit node but can't acces to nas data

### ISSUE THREAD

**Issue by farika** [ivokub/tailscale-qpkg#29]
Hi,

The exit node is working and well configured on tailscale website. Some i'm able to do :

Android-phone > NAS > Internet via exit node.

But i can't access NAS files from android phone when i try to go to my nas webinterface with :

https://Nastailscaleip:4443

or when i try to connect with android qnap app (qfiles etc...) to my nas and when using nas tailscaleip from tailscaleapp

All is working well when i'm the same lan network with wifi without tailscale.

I launched tailscale with the following command:

./tailscale -socket var/run/tailscale/tailscaled.sock up --advertise-exit-node

Edit : it is the qnap firewall, when off it's working... But can't manage to set the firewall well , if i autorise tailscale ip of my phone same issue

**Comment by ivokub** [comment]
Thanks, @farika.

I haven't tested with the QNAP firewall. Have you tried restricting the firewall gradually to see when the problems starts? For example:
1. no firewall
2. firewall enabled but allowing all incoming IPs to all services
3. firewall enabled and allowing local network and  100.0.0.0/8 to all services
4. firewall enabled and allowing local network and your phone tailscale ip to all services
5. firewall enabled and allowing local network and your phone tailscale ip to file sharing services

My personal QNAP is far away and I do not want risking testing the firewall configuration :)
