### ISSUE TITLE
Does this support the subnet router feature?

### ISSUE THREAD

**Issue by Europa2010AD** [ivokub/tailscale-qpkg#32]
Official Tailscale FAQ says subnet router is only supported in their Linux version at the moment. What about this qpkg?

**Comment by ivokub** [comment]
I haven't tried subnet router feature, but it works as an exit node. I would think that subet routing would work similarly, but I can not be sure. I can not try it out on my QNAP, but if you did, then please let know.

**Comment by matthewpucc** [comment]
I can confirm this works as a subnet router. This is currently how I use it.

**Comment by ivokub** [comment]
Thanks @matthewpucc for confirming. I'll keep the issue open for now - will update the readme later.

**Comment by jankatins** [comment]
So I can use this to access anything on my LAN in which the qnap is in? If so: how do I set it up, when I use the [app available in the qnapclub.eu store](https://www.qnapclub.eu/de/qpkg/1162), there is no UI to set any [commandline switches](https://tailscale.com/kb/1019/subnets/) :-(

**Comment by matthewpucc** [comment]
Just follow the instructions in the [readme](https://github.com/ivokub/tailscale-qpkg#installation) and add the [appropriate flags](https://tailscale.com/kb/1019/subnets/#:~:text=of%20Linux%20distros.-,Step%202%3A%20Connect%20to%20Tailscale%20as%20a%20subnet%20router,-Once%20installed%2C%20you) to the tailscale up command at the last step.

**Comment by Europa2010AD** [comment]
I can confirm the subnet router feature works perfectly after testing it out myself too. I tested it using both `ping` and `iperf3`. Thanks for the great work @ivokub !

@jankatins setting it up is easy with this repo (although I haven't tried the one from qnapclub.eu store). Say for example, if your QNAP's LAN IP is 192.168.1.1, and you want to expose the rest of your LAN within the same subnet (192.168.1.x). You just need to add the argument `--advertise-routes=192.168.1.0/24` when you start this Tailscale app, then head to your Tailscale admin console, you should see 192.168.1.0/24 appear in light grey under the TS IP address for your QNAP unit. Click on the "..." menu of the unit, the enable the subnet route. Voila! All set.
