### ISSUE TITLE
Changelog for v1.22.0?

### ISSUE THREAD

**Issue by Europa2010AD** [ivokub/tailscale-qpkg#33]
Is there anywhere I can see what changed in v1.22.0?

**Comment by guidoiaquinti** [comment]
> Is there anywhere I can see what changed in v1.22.0?

See the official upstream changelog [here](https://tailscale.com/changelog/)

**Comment by Europa2010AD** [comment]
Ahh didn't realize the Changelog here would be identical to the official TS one. Thanks for pointing that out!
