### ISSUE TITLE
How to configure this to auto-start after reboot?

### ISSUE THREAD

**Issue by Europa2010AD** [ivokub/tailscale-qpkg#34]
I noticed that after rebooting my QNAP, when I tried to run the "tailscaled.sock up" command, an error returned saying the daemon isn't running. I had to go to QNAP's App Center to start the app first, and then re-issue the "tailscaled.sock up" command.

Is there any way for me to set this to auto-start after rebooting?

**Comment by ivokub** [comment]
I'm not aware of any configurable option for starting the application automatically during startup. On my QNAP it starts automatically without any configuration.

Btw, you usually need to run `tailscale up` only once to connect the instance to your Tailnet. When the instance is already connected, then tailscale should connect to already-configured network.

**Comment by Europa2010AD** [comment]
Ahh perhaps my application didn't start after reboot because the reboot came from a firmware update. I'll have to test it out with a regular reboot and find out.

**Comment by ivokub** [comment]
@Europa2010AD - did you try?
