### ISSUE TITLE
How to built tailscale-qpkg to connect my headscale server

### ISSUE THREAD

**Issue by byangmath** [ivokub/tailscale-qpkg#35]
I want to use tailscale to connect my headscale server in my qnap (x86_64). Are there some ways to do this? Many thanks!

**Comment by ivokub** [comment]
Hi @byangmath,

I think there should be a way. When you follow the steps in the README, if you instead would use the command
```
./tailscale -socket var/run/tailscale/tailscaled.sock up --login-server https://your-headscale.example
```

I do not have a headscale server running nor can not try it out on my remote QNAP. Could you let know if this works?

**Comment by byangmath** [comment]
> Hi @byangmath,
> 
> I think there should be a way. When you follow the steps in the README, if you instead would use the command
> 
> ```
> ./tailscale -socket var/run/tailscale/tailscaled.sock up --login-server https://your-headscale.example
> ```
> 
> I do not have a headscale server running nor can not try it out on my remote QNAP. Could you let know if this works?

Thank you! It works!

**Comment by ivokub** [comment]
Great!
