### ISSUE TITLE
tailscale service keeps failing after 5 to 10 minutes

### ISSUE THREAD

**Issue by ithakaa** [ivokub/tailscale-qpkg#39]
I am running 

1.24.2
  go version: go1.18.1-ts710a0d8

on my qnap TS-219P

service keeps failing after 5 or 10 minutes

I do not see any logs in /var/log/messages

**Comment by ivokub** [comment]
Currently Tailscale daemon output is sent to `/dev/null`. You could manually start the daemon to see its output. Could you run `tailscaled` as in `Tailscale.sh` script without redirecting output to null.

**Comment by ithakaa** [comment]
I downgraded to a previous version, problem solved
