### ISSUE TITLE
Move Tailscale App to a new SSD

### ISSUE THREAD

**Issue by metheofanis** [ivokub/tailscale-qpkg#40]
I would like to move tailscale to my new SSD. I'm not getting the "Migrate" option as the other Apps. Did I miss something?

**Comment by ivokub** [comment]
I guess QPKG package should have a separate target for migrating the configuration which this current package has not implemented. I would need to look into how the migration target has to be implemented.

Meanwhile, as a manual override, it should be sufficient to just copy over `var/lib/tailscale/tailscaled.state` file in the Tailscale QPKG root directory to the new installation location. This file contains the private key of the local Tailscale node.
