### ISSUE TITLE
Installation is failing on QNAP NAS - assitance requested

### ISSUE THREAD

**Issue by FylBeall** [ivokub/tailscale-qpkg#41]
I've done an installation of https://github.com/ivokub/tailscale-qpkg/releases/download/v1.24.2/Tailscale_v1.24.2_x86_64.qpkg on this NAS but it does not seem to be completing correctly. Even though the NAS reports the installation completed, the Tailscale package directory does not exist at /share/CE_CACHEDEV1_DATA/.qpkg/Tailscale. Both the .qpkg and Tailscale directories do not exist.

When I open the tailscale app on the NAS, it brings up a window that has little contents other than options to stop or remove the app.

Here is the SSH session:

[~] # getcfg SHARE_DEF defVolMP -f /etc/config/def_share.info
/share/CACHEDEV1_DATA
[~] # cd /share
[/share] # ls
CACHEDEV1_DATA/  HDA_DATA/  HDD_DATA/  HDG_DATA/  HDJ_DATA/  HDM_DATA/  HDP_DATA/  HDS_DATA/  HDV_DATA/  HDY_DATA/  Laptop Backups@  Public@
Download@        HDB_DATA/  HDE_DATA/  HDH_DATA/  HDK_DATA/  HDN_DATA/  HDQ_DATA/  HDT_DATA/  HDW_DATA/  HDZ_DATA/  Multimedia@      Seagate Backup Plus Drive@
external/        HDC_DATA/  HDF_DATA/  HDI_DATA/  HDL_DATA/  HDO_DATA/  HDR_DATA/  HDU_DATA/  HDX_DATA/  homes@     Music@           Web@
[/share] # cd CACHEDEV1_DATA/
[/share/CACHEDEV1_DATA] # ls
aquota.user  Download/  homes/  Laptop Backups/  lost+found/  Multimedia/  Music/  Public/  Web/
[/share/CACHEDEV1_DATA] #

**Comment by ivokub** [comment]
Directories starting with `.` are hidden. Please show the output using the command `ls -a`.

**Comment by FylBeall** [comment]
Silly me. I knew that! That revealed the package directory and I was able to successfully connect. I'm good now.

Thanks for your help Ivo. But I am sorry to have wasted your time with such simple thing.

**Comment by ivokub** [comment]
All good! Glad to see you got it resolved.
