### ISSUE TITLE
can't ping nas / failed to connect to local tailscaled / Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by roger-richards** [ivokub/tailscale-qpkg#42]
I have successfully (I think) installed tailscale 1.24.2 _x86_64.qpkg on my QNAP TS-453Be. 
**UPDATE - I turned off QuFirewall and it WORKED. Now I need to find the rule that allows tailscale connection.
Any suggestions?**

_I ssh into qnap and interact with tailscale via CLI. When I try: ./tailscale up
I get:
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 31923). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

I've made sure the tailscaled daemon was running via CLI with sudo ./tailscaled
netcheck Report:
	* UDP: true
	* IPv4: yes, 172.58.23.48:38273
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: 
	* Nearest DERP: San Francisco
	* DERP latency:
		- sfo: 30.2ms  (San Francisco)_

**Comment by ivokub** [comment]
Great that you got it working. I haven't tested out different firewall rules, but could you have a look at https://github.com/ivokub/tailscale-qpkg/issues/29#issuecomment-986323703, if there is a least-exposing rule for your needs? If your QNAP is on the public internet then it makes sense to restrict the network down.

**Comment by byangmath** [comment]
Everytime I update my tailscale on QNAP (I used headscale as the server), it will be disconnected. I tried: ./tailscale up, but I got
```
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 7611). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

If I restart QNAP, it works.

**Comment by ivokub** [comment]
> Hi @ivokub. Everytime I update my tailscale on QNAP (I used headscale as the server), it will be disconnected. I tried: ./tailscale up, but I got
> 
> ```
> failed to connect to local tailscaled (which appears to be running as tailscaled, pid 7611). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
> ```
> 
> If I restart QNAP, it works.

The socket for communicating between daemon and client is in non-standard location. Instead `cd` to Tailscale QPKG directory and run `./tailscale -socket var/run/tailscale/tailscaled.sock up`

**Comment by byangmath** [comment]
> 

It works! Many thanks!
