### ISSUE TITLE
TS-212-E "failed to connect to local tailscaled;"

### ISSUE THREAD

**Issue by Amorget** [ivokub/tailscale-qpkg#44]
I installed Tailscale on my TS-212-E.  I was able to successfully install it on my TS-253-D so I had an idea what to do.

Installed the ARM-x19 package, which according to the log installed and started, 
Type	Date	Time	Users	Source IP	Computer name	Content	
Information	2022/08/11	19:41:21	System	127.0.0.1	localhost	[App Center] Installed Tailscale v1.28.0 in /share/HDA_DATA/.qpkg/Tailscale.
Information	2022/08/11	19:41:33	System	127.0.0.1	localhost	[App Center] Enabled Tailscale.	

However when attempting the up I am getting this:

<scale] # ./tailscale -socket var/run/tailscale/tailscaled.sock up             
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)

Tried rebooting the NAS but that made no difference.

I am a bit lost as to where to go from here.

**Comment by ivokub** [comment]
Strange, seems related to #43. As it is already a second report with same symptoms, then it may be something systematic with QNAP.
Are you able to manually start tailscale with `./Tailscale.sh start` in the package directory?

**Comment by Amorget** [comment]
It doesn't seem like it

[/share/HDA_DATA/.qpkg/Tailscale] # ./Tailscale.sh start
<lscale -socket var/run/tailscale/tailscaled.sock up    
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)

It pauses for a couple seconds after the start command but it doesn't seem to start, but no error either.

**Comment by ivokub** [comment]
Hmm. The startup script writes logs to /dev/null (I hadn't figured out a good place to write the logs) and we don't see if the daemon fails. Can you try in the package directory:
```
tailscaled --port 41641 --state=var/lib/tailscale/tailscaled.state --socket=var/run/tailscale/tailscaled.sock
```

Does it error?

**Comment by Amorget** [comment]
It does error

<ailscale/tailscaled.state --socket=var/run/tailscale/tailscaled.sock        
logtail started
Program starting: v1.28.0-taabca3a4c, Go 1.18.4-ts149f7d8: []string{"./tailscaled", "--port", "41641", "--state=var/lib/tailscale/tailscaled.state", "--socket=var/run/tailscale/tailscaled.sock"}
LogID: 805520e70c4b92b9c6fac0c1b18c4c7f6ca879c9576444509e14b3f41a99bb58
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 3.4.6
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: could not parse modules.dep

wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): no such device
flushing log.
logger closing down
createEngine: tstun.New("tailscale0"): no such device

**Comment by ivokub** [comment]
OK, I see. Can you try installing the official QVPN app from the app store? I think it should install the tun module. Just installing it should be sufficient, no need to configure or run it.

It is not required for the latest QTS (see #22), but I guess is necessary for older versions.

**Comment by Amorget** [comment]
That fixed it.

My QTS version is 4.3.3.2057, in case that helps anyone in the future.  The 212 isn't supported by the newer versions so that's as updated as it gets from a major release perspective.

**Comment by majido** [comment]
Just wanted to report that the same issue happened to my on a TS-412 model with `Tailscale_v1.30.1_arm-x19.qpkg` and suggested workaround of installing QVPN fixed the issue. Thanks for creating this application. 🔥
